apiVersion: v1
kind: Service
metadata:
  name: user-app-svc
  labels:
    app: user-app
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: user-app
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: eu.gcr.io/public-data4life/covid-19-mapview-user-app:master-20200404124505-2e87b76
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: "/usr/share/nginx/html/config.js"
              subPath: "config.js"
          env:
            - name: REACT_APP_GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: user-app-map-credentials
                  key: map_token
      volumes:
        - name: config-volume
          configMap:
            name: user-app-config
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: user-app-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"

spec:
  rules:
    - host: app.data4life.se
      http:
        paths:
          - path: /
            backend:
              serviceName: user-app-svc
              servicePort: 80
          - path: /*
            backend:
              serviceName: user-app-svc
              servicePort: 80
